### PR TITLE
update background color in "state" block

### LINKED ISSUE #778: [FEATURE] Make background color in "state" block of edit index management not hardcoded
**Is your feature request related to a problem?**
1. Go To Index Management
2. Navigate To Index Policies
3. Select a policy and edit via policy editor
4. Go to the States

The background color of "states" is hardcoded to a whitish color, which will clash with overall theme color of UI when in dark mode.

image

**What solution would you like?**
Color of 'state' section appear to be hardcoded here:

https://github.com/opensearch-project/index-management-dashboards-plugin/blob/main/public/pages/VisualCreatePolicy/components/States/State.tsx

line 105:

`<EuiFlexGroup direction="column" style={{ backgroundColor: "#f8f9fc" }}>`

It would be nice if this could be changed to either dynamically adjust according to "main" theme of the UI (i.e darkMode)

### PR DESCRIPTION
**Pull request by wrch0712**
### Description
Update background color in "state" block

### Issues Resolved

#778 
The background color of "states" is hardcoded to a whitish color, which will clash with overall theme color of UI when in dark mode.

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by bowenlan-amzn** [comment]
@wrch0712 thanks for raising this PR. Can you post the screenshot comparison before and after your change please.

**Comment by wrch0712** [comment]
@bowenlan-amzn Sure! Before the change, the page looked exactly as described in the issue. Here is a screenshot after the change.
截屏2023-11-01 下午2 23 21

**Review by bowenlan-amzn — APPROVED** [review]

**Review by AWSHurneyt — DISMISSED** [review]

**Comment by bowenlan-amzn** [comment]
@wrch0712 I notice there are unit test failure. Can you try fix those please

**Comment by bowenlan-amzn** [comment]
@wrch0712 can you run yarn run test:jest -u to update the test snapshot and push the change, thanks

**Review by Hailong-am — APPROVED** [review]
If it is possible to have a screenshot of this change, that will be helpful for reviewing.

**Pull request merged**
