### PR TITLE
Remove node version declaration in package.json

### LINKED ISSUE #137: Ensure plugins work with Dashboards Node v14.18.2
Dashboards has upgraded Node to v14.18.2 and this is for plugin teams to verify that their plugins work with the new version upgrade. The Dashboards branch running the upgraded node is [feature/node14](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/feature/node14).

A list of things to check is:
* Your plugin's node version is bumped to 14.18.2
* Your plugin's `@types/node` package is bumped to `^14.17.32` if it's used
* Plugin builds and runs on Dashboards
* All of your plugin's tests pass
* Your GitHub workflows are not broken by the node version change and updated if they do
* Any sanity/smoke testing is successful

### PR DESCRIPTION
**Pull request by annie3431**
Signed-off-by: Annie Lee leeyun@amazon.com

### Description
Remove explicit declaration in `package.json` file. This will inherit the node version from Opensearch-Dashboards core. 
Checked that the node version will match with core dashboards in [this workflow](https://github.com/leeyun-amzn/index-management-dashboards-plugin/runs/5399445951?check_suite_focus=true) (check "Set up node" step) both are using 14.18.2 

### Issues Resolved
#137 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by downsrob** [comment]
Based on the SOP for upgrading node versions it looks like the @types/node version should be bumped as well

**Comment by leeyun-amzn** [comment]
> Based on the SOP for upgrading node versions it looks like the @types/node version should be bumped as well

Thanks for checking! I removed that line in `package.json` too.

**Review by dbbaughe — APPROVED** [review]

**Comment by downsrob** [comment]
I don't know much about node so I could be off but it looks like this is still left in the yarn.lock:
https://github.com/opensearch-project/index-management-dashboards-plugin/blob/13826eb29f4323735228e1d06efef085846b856f/yarn.lock#L245-L249
Wouldn't `@types/node@*` mean that any types/node version you use will resolve to version `10.12.27` even if you set it to be something different in package.json? 
Here is the block on OpenSearch Dashboards 
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/yarn.lock#L3189-L3193

**Comment by leeyun-amzn** [comment]
> I don't know much about node so I could be off but it looks like this is still left in the yarn.lock:
> 
> https://github.com/opensearch-project/index-management-dashboards-plugin/blob/13826eb29f4323735228e1d06efef085846b856f/yarn.lock#L245-L249
> 
> Wouldn't `@types/node@*` mean that any types/node version you use will resolve to version `10.12.27` even if you set it to be something different in package.json?
> Here is the block on OpenSearch Dashboards
> https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/yarn.lock#L3189-L3193

Checking

**Comment by bowenlan-amzn** [comment]
Will open another one for this.

**Pull request closed without merging**
