### PR TITLE
Interface change for MDS and deprecating dataSourceLabel from the URL…

### PR DESCRIPTION
**Pull request by RamakrishnaChilaka**
… (#1031)

Signed-off-by: Ramakrishna Chilaka <ramachil@amazon.com>
(cherry picked from commit ed98e4ab820ebe7fd436548a4e0793757a4cbb30)

### Description
[Describe what this change achieves]

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by RamakrishnaChilaka** [comment]
CI will pass post the following PR merge...

https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1025

**Comment by BionIT** [comment]
Hi @RamakrishnaChilaka , I tried to pull the branch and saw 400 error for http://localhost:5601/api/ism/apiCaller, see screenshot below
Screenshot from 2024-04-14 16-44-06
Looks like schema validation error, could you fix? Happy to take another look

**Comment by RamakrishnaChilaka** [comment]
Thanks Lu. @BionIT, The above issue is fixed in `main` branch and it would be fixed post the following backport PR merge.

https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1025

**Comment by RamakrishnaChilaka** [comment]
Closing in favour of "https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1036"

**Pull request closed without merging**
