### PR TITLE
adding cancel button to change policy

### LINKED ISSUE #840: [BUG] Missing cancel button in Change policy page
**What is the bug?**
In the 'Change policy' page, users don't have a clear path to leave the page if they decided not to change policies.
image

**How can one reproduce the bug?**
1. Go to 'Index Management'
2. Go to 'Policy managed indexes'
3. Click on 'Change policy' button

**What is the expected behavior?**
Next to the 'Change' button, there should be a button called Cancel that will take users back to the 'Policy managed indexes' page.

Use [OuiButtonEmpty](https://oui.opensearch.org/1.2/#/navigation/button#empty-button), Primary for the Cancel button:
image

### PR DESCRIPTION
**Pull request by kohinoor98**
### Description
Added Cancel button to `ChangePolicy.tsx`

### Issues Resolved
#840 

### Check List
- [x] Commits are signed per the DCO using --signoff
- [x] Test the `Cancel` button in Change Policy page

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by AWSHurneyt** [comment]
@kohinoor98 looks like some snapshot unit tests failed. Could you run `yarn run test:jest -u`? That will update the snapshots, and should allow the unit tests to pass.

**Comment by kohinoor98** [comment]
Hi @AWSHurneyt 

The current test case that is failing is addressed in this PR #918. 

Please advice on next steps.

Thanks,
KC

**Comment by AWSHurneyt** [comment]
@kohinoor98 Looks like there's still a unit test failing in the `ChangePolicy.test.tsx`.
https://github.com/opensearch-project/index-management-dashboards-plugin/actions/runs/6805289930/job/18504495378?pr=919#step:10:860

I see in the commits tab for this PR that changes from the `main` branch were merged into the dev branch for this PR after the snapshot was updated. Could you try running `yarn run test:jest -u` again? If that doesn't resolve the failing test, it may need deeper investigation.

**Review by bowenlan-amzn — APPROVED** [review]

**Comment by kohinoor98** [comment]
Hi @AWSHurneyt 

I have updated the PR with the latest code from `yarn run test:jest -u` for the cancel button.

I tested snapshots_spec.js on cypress and it kept failing in `one to three` of the test cases  for some reason or the other over 10 runs. 

I am guessing @bowenlan-amzn noticed the same and created #925 for the same.

Thanks,
KC

**Review by AWSHurneyt — APPROVED** [review]

**Pull request merged**
