### PR TITLE
Fit and finish changes for Aliases, Templates and Policy managed Indices pages

### PR DESCRIPTION
**Pull request by tandonks**
### Description
Fit and finish changes for Aliases, Templates and Policy managed Indices pages

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by danieldong51** [comment]
Is this modal in scope?
`public/pages/Aliases/containers/DeleteAliasModal/DeleteAliasModal.tsx`
Delete Modal

**Comment by danieldong51** [comment]
Header size in `public/pages/CreateIndexTemplate/containers/TemplateDetail/TemplateDetail.tsx`?

Create Template

**Comment by danieldong51** [comment]
A few modals in Templates use the SimpleModal in `public/components/Modal/Modal.tsx` and should be `h2` tags wrapped in `EuiText size="s"`, is this in scope?

| Associate Component Template | Create component template |
| ---- | ---- |

**Comment by danieldong51** [comment]
This flyout in `public/pages/Templates/containers/AssociatedComponentsModal/AssociatedComponentsModal.tsx`:

Associated component flyout

**Comment by danieldong51** [comment]
Is the header in `public/pages/ChangePolicy/containers/ChangePolicy/ChangePolicy.tsx` in scope?

Change Policy

**Comment by danieldong51** [comment]
The text in `public/pages/Policies/components/PolicyEmptyPrompt/PolicyEmptyPrompt.tsx` should be small:

Delete Modal

**Review by danieldong51 — APPROVED** [review]

**Review by SuZhou-Joe — APPROVED** [review]

**Pull request merged**
